### ISSUE TITLE
Non-HTTPS sites are not accessible

### ISSUE THREAD

**Issue by TimothyBJacobs** [TablePlus/TinyWeb-issue-tracker#1]
They fail with the following error message:

> URLSessionTask failed with error: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.

Often times when developing locally I don't have HTTPS set up.

**Comment by huyphams** [comment]
Hi @TimothyBJacobs can you show me the gif? TinyWeb auto append http to the URL if you forgot to enter it.

**Comment by huyphams** [comment]
I can load localhost with port without any issue, so I'm not sure how to reproduce the issue.

**Comment by TimothyBJacobs** [comment]
You can try `http://neverssl.com` and you'll see the error.

<img width="1286" alt="Screenshot 2024-05-05 at 12 03 50 PM" src="https://github.com/TablePlus/TinyWeb-issue-tracker/assets/3460448/1c6fde9e-bafd-4e4e-8a68-121d376915f6">

App Transport Security allows `localhost`, but often when developing locally you'll have a URL like `http://mysite.test`.

**Comment by huyphams** [comment]
Ah I see, so let me try to disable it.

**Comment by huyphams** [comment]
Fixed! Thank you @TimothyBJacobs you can update the app by go to Main menu TinyWeb > Check for updates...
