### ISSUE TITLE
Feature Request: Add option to make the options menu visible

### ISSUE THREAD

**Issue by raphaelluethy** [TablePlus/TinyWeb-issue-tracker#10]
Since I use mostly POST requests with body or headers, I would really appreciate if the way to access any other request types and headers/body would be better visible and not hidden behind a `settings` icon. Having a setting to have them open by default or a shortcut would be great!

**Comment by huyphams** [comment]
Yup @raphaelluethy we will find aways to improve it.

**Comment by huyphams** [comment]
You can press the Command + E to toggle it @raphaelluethy

**Comment by raphaelluethy** [comment]
thanks a lot @huyphams
