### ISSUE TITLE
Not following 301 redirects

### ISSUE THREAD

**Issue by kawikak** [TablePlus/TinyWeb-issue-tracker#11]
### The steps to reproduce this issue:

Does not follow 301 redirects for sites behind a reverse proxy, cloudflare, etc.

**Comment by huyphams** [comment]
Hi @kawikak, this is intentional. We do not follow redirects. Maybe we should add an option where the user wants the app to follow redirects.

**Comment by kawikak** [comment]
It would be great to have an option for that. Most of the sites I wish to try it with are in a shared hosting environment and are proxied behind redirects or are hosted behind Cloudflare. I really like the potential of the app though, great work!

**Comment by huyphams** [comment]
We added an option to allow follow redirect on URL https://www.dropbox.com/scl/fi/fpmggw40az86u1thpfycd/TinyWeb.zip?rlkey=3fmeeig9r3pddggww18maumjf&dl=0

<img width="1144" alt="Screenshot 2024-05-07 at 12 52 17 PM" src="https://github.com/TablePlus/TinyWeb-issue-tracker/assets/3654622/b8c4504d-197f-47d8-80f3-9fcf4a204948">

**Comment by kawikak** [comment]
That works great, thanks!
