### ISSUE TITLE
Window.open doesn't work

### ISSUE THREAD

**Issue by Rusya13** [TablePlus/TinyWeb-issue-tracker#16]
### The steps to reproduce this issue:
- Open https://musicpiechart.com
- Click Login to Spotify
- The new window expects with a redirect to Spotify auth page

It looks like window.open doesn't work and a new window is not appearing.

**Comment by huyphams** [comment]
Thanks @Rusya13 we will fix this.

**Comment by huyphams** [comment]
It works on my end, can you check it again? Are you using our latest release 21?
https://github.com/TablePlus/TinyWeb-issue-tracker/assets/3654622/e2f2de3d-e8d6-4bfd-b9f2-c511a28615ac

**Comment by Rusya13** [comment]
It is a latest release, yes.

It is working after closing and opening it again. But the next problem after coming back was to the main window is losing the ability to click anywhere.

**Comment by huyphams** [comment]
Hi @Rusya13 the build 38 should fix this issue. Let me know if you're still seeing it.
Thanks!
