### ISSUE TITLE
URL without https:// will not open

### ISSUE THREAD

**Issue by patrickmast** [TablePlus/TinyWeb-issue-tracker#18]
I encounter these errors frequently:

![Image](https://github.com/TablePlus/TinyWeb-issue-tracker/assets/424387/ea580b06-2eaa-41bf-a4ae-f41195933009)

This error is specific to www.xano.com. Visiting https://www.xano.com resolves the issue, as does visiting other websites. Without the https:// prefix, the site fails to load.

**Comment by huyphams** [comment]
Hi @patrickmast We design TinyWeb with the setting do not follow redirect by default (because it is a HTTP client not the browser in the first place), so you can enable the follow redirect in the advance mode (the button on the next of the search) for the URL you want  TinyWeb follow redirects.

**Comment by huyphams** [comment]
But we think that we should enable it by default (and user can turn off it), because user mainly use the app for web browsing

**Comment by huyphams** [comment]
The auto follow redirect enable by default now.
