### ISSUE TITLE
Window's "Traffic light controls" dots visible

### ISSUE THREAD

**Issue by patrickmast** [TablePlus/TinyWeb-issue-tracker#19]
Can we auto-hide these?
![image](https://github.com/TablePlus/TinyWeb-issue-tracker/assets/424387/e30a2187-3538-4afb-9a02-11b48aa3a2ae)

**Comment by huyphams** [comment]
Yes, there is an option where you can auto hide it. I think you have created the app with the option dedicated window control button?
Did you choose option 2? You should choose option 1 - default.
<img width="652" alt="Screenshot 2024-05-10 at 6 24 06 PM" src="https://github.com/TablePlus/TinyWeb-issue-tracker/assets/3654622/bb3e3ae2-65a9-40bf-8ba5-4d8cf4b07efe">

**Comment by patrickmast** [comment]
It's on the main TinyWeb app, not a newly created one. 😉

**Comment by huyphams** [comment]
Hmm could you tell me how to reproduce the issue?

**Comment by huyphams** [comment]
Oh i see, it will show after the app back from maximize.

**Comment by patrickmast** [comment]
Correct! ;-)

**Comment by huyphams** [comment]
Fixed on build 31! You can update the app now!

**Comment by patrickmast** [comment]
Sorry, still here with me: 
![image](https://github.com/TablePlus/TinyWeb-issue-tracker/assets/424387/5e08a376-6e0e-4594-bdd7-3efd3b5179c5)

**Comment by huyphams** [comment]
Hi @patrickmast which build are you using?

**Comment by patrickmast** [comment]
Using version 1.3.7, the traffic light controls remain fixed when I maximize or unmaximize the window. I use BetterTouchTool to automatically resize my window, causing the traffic light controls to appear.

**Comment by huyphams** [comment]
Ah okie so the Window is resized by another application. Let me check it.

**Comment by huyphams** [comment]
Hi @patrickmast I think the build 38 would fix the issue.

**Comment by patrickmast** [comment]
Yes, fixed! Thanks! 👍
