### ISSUE TITLE
Can we have a keyboard shortcut to go "Back"?

### ISSUE THREAD

**Issue by patrickmast** [TablePlus/TinyWeb-issue-tracker#3]
Like the default CMD-[ on any browser?

**Comment by innocenzi** [comment]
MB4 and MB5 (which by default act as backward/forward in all UIs) would be great as well

**Comment by huyphams** [comment]
The default shortcut is command + arrow left/right but we can add more and allow the user to customize it

**Comment by patrickmast** [comment]
Shortcut is command + arrow left/right is perfect! Thanks!

**Comment by huyphams** [comment]
Added swipe gestures!
