### ISSUE TITLE
Multiple windows and/or instances.

### ISSUE THREAD

**Issue by patrickmast** [TablePlus/TinyWeb-issue-tracker#5]
Can we have multiple TinyWeb windows or instances. Each instance can have its own icon. This feature enables the creation of headless web applications using TinyWeb, making it even more powerful and versatile.

**Comment by huyphams** [comment]
We are working on this

**Comment by huyphams** [comment]
Added on ver 9. Thanks!

**Comment by patrickmast** [comment]
Thank you!
