### ISSUE TITLE
UI dark, really dark.

### ISSUE THREAD

**Issue by patrickmast** [TablePlus/TinyWeb-issue-tracker#7]
Really dark theme ;-)
![image](https://github.com/TablePlus/TinyWeb-issue-tracker/assets/424387/b4b466d8-6cb4-468e-9384-47076d8e5461)
![image](https://github.com/TablePlus/TinyWeb-issue-tracker/assets/424387/515ecba4-5362-4c0d-beec-f926f775496b)

**Comment by huyphams** [comment]
Hi @patrickmast are you switching theme?

**Comment by patrickmast** [comment]
Hi @huyphams, no, just starting TinyWeb. Did not know you can switch themes in TinyWeb?

**Comment by huyphams** [comment]
Hmm I could not reproduce the issue. Could you restart the app and see how it goes?

**Comment by patrickmast** [comment]
Restarted and same :)

**Comment by huyphams** [comment]
Weird, could you please try this build and see how it goes?
https://www.dropbox.com/scl/fi/fpmggw40az86u1thpfycd/TinyWeb.zip?rlkey=3fmeeig9r3pddggww18maumjf&dl=0
Thanks

**Comment by patrickmast** [comment]
Works now! Thanks!!

Just a minor detail – the background of the slidover now matches the webpage color. Maybe consider making the slidover darker?
![image](https://github.com/TablePlus/TinyWeb-issue-tracker/assets/424387/71576bba-1ee2-4da5-8a96-d6c22b1ade07)

**Comment by huyphams** [comment]
Thanks I just add the visual effect so it will be a little bit blur + darker than any website background.
