### ISSUE TITLE
Multiple instances of TinyWeb

### ISSUE THREAD

**Issue by patrickmast** [TablePlus/TinyWeb-issue-tracker#8]
Continuing from https://github.com/TablePlus/TinyWeb-issue-tracker/issues/5:

Could we additionally implement the ability to create a new instance of TinyWeb and customize its icon? Each instance can be individually placed on the Dock with a unique icon. This feature enhances TinyWeb's capabilities, allowing for the development of headless web applications and further expanding its power and versatility! 🚀

**Comment by huyphams** [comment]
Yes, it is one of our goals.

**Comment by huyphams** [comment]
We posted it here @patrickmast https://twitter.com/TablePlus/status/1787443205518070131

**Comment by huyphams** [comment]
This feature is ready :) I'm polishing it and it will be release tomorrow!

**Comment by patrickmast** [comment]
Wow, that's just GREAT!! Can't wait to test! 🚀

**Comment by huyphams** [comment]
You can see it here
https://x.com/tableplus/status/1787896543976083466?s=46

**Comment by huyphams** [comment]
Released on build 21 but still beta testing and adding more features!
