### ISSUE TITLE
Topbar disappears when going to `Raw` mode and is too hard to make reappear

### ISSUE THREAD

**Issue by raphaelluethy** [TablePlus/TinyWeb-issue-tracker#9]
### The steps to reproduce this issue:
- open website
- open `raw` mode
- hover to contents with cursor
 
to make the topbar reappear again, you have to go up to the top border of the app.

Fix suggestion: 
- Add shortcut to switch between `pretty` and `raw`
- make hover zone on top bigger
- add some button to make topbar appear

**Comment by huyphams** [comment]
Maybe we should use the command + I or command + option  + I as the default keyboard of any browsers.

**Comment by raphaelluethy** [comment]
That might be a great idea

**Comment by huyphams** [comment]
You can try this build: https://www.dropbox.com/scl/fi/fpmggw40az86u1thpfycd/TinyWeb.zip?rlkey=3fmeeig9r3pddggww18maumjf&dl=0
It has shortcut command + I (alias command + option + I) to toggle the views.

**Comment by raphaelluethy** [comment]
feels quite nice, makes the switch way easier :) 👍

**Comment by huyphams** [comment]
Also available via in app update now @raphaelluethy build 14
